-- 添加 User 实体中缺失的列
ALTER TABLE `users`
ADD COLUMN IF NOT EXISTS `phone` VARCHAR(20) UNIQUE NULL COMMENT '手机号',
ADD COLUMN IF NOT EXISTS `passwordHash` VARCHAR(256) NULL COMMENT '密码哈希',
ADD COLUMN IF NOT EXISTS `nickname` VARCHAR(64) NULL COMMENT '昵称',
ADD COLUMN IF NOT EXISTS `avatar` VARCHAR(512) NULL COMMENT '头像URL',
ADD COLUMN IF NOT EXISTS `gender` ENUM('male', 'female', 'other') NULL COMMENT '性别',
ADD COLUMN IF NOT EXISTS `birthDate` DATE NULL COMMENT '生日',
ADD COLUMN IF NOT EXISTS `location` VARCHAR(256) NULL COMMENT '所在地',
ADD COLUMN IF NOT EXISTS `bio` TEXT NULL COMMENT '个人简介',
ADD COLUMN IF NOT EXISTS `emailVerified` BOOLEAN DEFAULT FALSE COMMENT '邮箱是否已验证',
ADD COLUMN IF NOT EXISTS `phoneVerified` BOOLEAN DEFAULT FALSE COMMENT '手机是否已验证',
ADD COLUMN IF NOT EXISTS `lastLoginAt` TIMESTAMP NULL COMMENT '最后登录时间',
ADD COLUMN IF NOT EXISTS `lastLoginIp` VARCHAR(64) NULL COMMENT '最后登录IP';

-- 添加索引
CREATE INDEX IF NOT EXISTS `IDX_users_phone` ON `users` (`phone`);
